### ISSUE TITLE
Can not connect to a BlazeDS server & Authentication issue

### ISSUE THREAD

**Issue by waeljammal** [nesium/cocoa-amf#4]
Try connecting to a BlazeDS back end configured with Spring which works fine in Flex but cocoa-amf reports No destination with id 'destination name' exists.

The other issue is there is no way to authenticate on a BlazeDS server that has been configured to use channelset authentication, is the only other work around to create a standard method for handling authentication?

**Comment by nesium** [comment]
i think if you'd create a amfactionmessage, add a body where the targetURI is @"null" and the data is a properly configured instance of FlexRemotingMessage and also add a header with the name @"DSRemoteCredentials" which carries the credentials base64 encoded, everything should just work fine (i think).

**Comment by sarbogast** [comment]
It's not a demand, just something I need to know in order to decide whether I'm going to stick with AMF or find another solution: do you plan to implement authentication into your framework soon?
By the way, I've heard that Adobe will release AMF components for iOS (as well as Javascript, .Net and others) but in a commercial fashion under the roof of LCDS offer. So your library might be the only Open Source alternative to that.
